[package]
name = "component-test-sdk"
description = "Guest SDK for lann:component-test suites"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
component-test-core = { workspace = true }
component-test-sdk-macro = { workspace = true }
