//! The inventory lockfile: every case name + its feature tags, in
//! suite order, bound to a suite artifact. TOML, generated, reviewed as
//! diffs.
//!
//! Generated rows are prefix-granular by default (leaves exist only at
//! enumeration time). A lockfile generated with an enumeration input
//! (`lock --leaves`, fed from a runner's `--enumerate`) additionally
//! pins each row's leaves (`cases`, one per line), and
//! [`Lockfile::check_coverage`] then holds reported leaves to exact
//! set equality — the same census exact cases get (#49).
//!
//! Lints enforced by [`Lockfile::validate`]:
//! - name grammar + duplicate names (hard error), including each
//!   enumerated leaf under its prefix
//! - decline-pair: every feature named by a positive mark is named by
//!   at least one negative-marked case

use std::collections::{BTreeMap, BTreeSet};

use anyhow::{bail, Context as _};
use component_test_core::{CaseName, Tag};
use serde::{Deserialize, Serialize};

pub const LOCKFILE_VERSION: &str = "0.1";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Lockfile {
    /// Format version.
    pub version: String,
    /// The suite this inventory was generated from.
    pub suite: SuiteRef,
    /// Every statically-known case, in canonical order. Empty for
    /// all-generated suites (TOML omits empty table arrays, so this
    /// must default on deserialization or `lock`'s own output for such
    /// a suite wouldn't re-parse).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub case: Vec<CaseEntry>,
    /// Generated rows: leaves enumerated at run time under a static
    /// prefix, sharing the row's tags.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub generated: Vec<GeneratedEntry>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct GeneratedEntry {
    /// Name prefix (every segment a WIT label); cases live at
    /// `prefix/<leaf...>`.
    pub prefix: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<Tag>,
    /// The row's enumerated leaves (case names relative to the
    /// prefix), in suite order, when the lockfile was generated with
    /// an enumeration input. Present: coverage holds the row to exact
    /// set equality. Absent: prefix-granular coverage (an
    /// enumeration-free lockfile keeps working).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub cases: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct SuiteRef {
    pub name: String,
    /// sha256 of the suite component artifact this inventory was
    /// generated from, hex. Provenance, not identity: suite builds are
    /// not reproducible across environments, so consumers MUST NOT
    /// require this to equal a hash computed elsewhere (a lockfile
    /// committed from one machine will not match a source-identical CI
    /// build). Opportunistic uses — cache keys, same-machine staleness
    /// detection — are fine. The authoritative binding between results
    /// and a lockfile is the inventory itself (names + tags).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub artifact_sha256: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CaseEntry {
    pub name: CaseName,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<Tag>,
}

impl Lockfile {
    pub fn new(suite: SuiteRef, cases: Vec<CaseEntry>) -> Self {
        Self::with_generated(suite, cases, Vec::new())
    }

    pub fn with_generated(
        suite: SuiteRef,
        cases: Vec<CaseEntry>,
        generated: Vec<GeneratedEntry>,
    ) -> Self {
        Lockfile {
            version: LOCKFILE_VERSION.to_string(),
            suite,
            case: cases,
            generated,
        }
    }

    /// Render as TOML. Hand-emitted rather than serde-serialized: a
    /// generated row's `cases` enumeration must render one leaf per
    /// line to stay a reviewable diff surface, and the pretty printer
    /// renders string arrays inline. Byte-compatible with the previous
    /// serde output for enumeration-free lockfiles (pinned by the
    /// `emission_format` test); parsing stays serde.
    pub fn to_toml(&self) -> anyhow::Result<String> {
        fn quoted(s: &str) -> String {
            format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
        }
        fn tags_line(tags: &[Tag]) -> String {
            let items: Vec<String> = tags.iter().map(|t| quoted(&t.to_string())).collect();
            format!("tags = [{}]\n", items.join(", "))
        }
        let mut out = String::new();
        out.push_str("# Generated by component-test; do not edit.\n");
        out.push_str(&format!("version = {}\n", quoted(&self.version)));
        out.push_str("\n[suite]\n");
        out.push_str(&format!("name = {}\n", quoted(&self.suite.name)));
        if let Some(hash) = &self.suite.artifact_sha256 {
            out.push_str(&format!("artifact_sha256 = {}\n", quoted(hash)));
        }
        for case in &self.case {
            out.push_str("\n[[case]]\n");
            out.push_str(&format!("name = {}\n", quoted(&case.name.as_str())));
            if !case.tags.is_empty() {
                out.push_str(&tags_line(&case.tags));
            }
        }
        for gen in &self.generated {
            out.push_str("\n[[generated]]\n");
            out.push_str(&format!("prefix = {}\n", quoted(&gen.prefix)));
            if !gen.tags.is_empty() {
                out.push_str(&tags_line(&gen.tags));
            }
            if !gen.cases.is_empty() {
                out.push_str("cases = [\n");
                for leaf in &gen.cases {
                    out.push_str(&format!("    {},\n", quoted(leaf)));
                }
                out.push_str("]\n");
            }
        }
        Ok(out)
    }

    pub fn from_toml(s: &str) -> anyhow::Result<Self> {
        let lf: Lockfile = toml::from_str(s).context("parsing lockfile")?;
        Ok(lf)
    }

    /// Grammar/duplicate/decline-pair lints. Returns the set of features
    /// referenced by tags on success.
    pub fn validate(&self) -> anyhow::Result<BTreeSet<String>> {
        if self.version != LOCKFILE_VERSION {
            bail!("unsupported lockfile version {}", self.version);
        }
        let mut seen = BTreeSet::new();
        for entry in &self.case {
            if !seen.insert(entry.name.clone()) {
                bail!("duplicate case name `{}`", entry.name);
            }
            component_test_core::Tags::new(entry.tags.clone())
                .map_err(|e| anyhow::anyhow!("case `{}`: {e}", entry.name))?;
        }
        let mut prefixes = BTreeSet::new();
        for gen in &self.generated {
            if !prefixes.insert(gen.prefix.as_str()) {
                bail!("duplicate generated prefix `{}`", gen.prefix);
            }
            // Same rule the inventory scanner and the macro enforce:
            // every prefix segment is a WIT label (leaves are appended
            // below it). A lockfile is the gate for foreign/hand-made
            // producers, so it must not be the one validator with the
            // hole.
            for seg in gen.prefix.split('/') {
                if let Some(reason) = component_test_core::name::is_wit_label(seg) {
                    bail!(
                        "generated prefix `{}`: segment `{seg}` is not a WIT label ({reason})",
                        gen.prefix
                    );
                }
            }
            component_test_core::Tags::new(gen.tags.clone())
                .map_err(|e| anyhow::anyhow!("generated `{}`: {e}", gen.prefix))?;
            let mut leaves = BTreeSet::new();
            for leaf in &gen.cases {
                CaseName::parse(&format!("{}/{leaf}", gen.prefix)).map_err(|e| {
                    anyhow::anyhow!("generated `{}` leaf `{leaf}`: {e}", gen.prefix)
                })?;
                if !leaves.insert(leaf.as_str()) {
                    bail!("generated `{}`: duplicate leaf `{leaf}`", gen.prefix);
                }
            }
        }
        let unpaired = component_test_core::tags::unpaired_positive_features(
            self.case
                .iter()
                .map(|c| c.tags.as_slice())
                .chain(self.generated.iter().map(|g| g.tags.as_slice())),
        );
        if !unpaired.is_empty() {
            bail!(
                "decline-pair lint: feature(s) {} have positively-marked cases but no \
                 `!feature` decline-asserting case",
                unpaired
                    .iter()
                    .map(|f| format!("`{f}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }
        let mut features: BTreeSet<String> = BTreeSet::new();
        for tag in self
            .case
            .iter()
            .flat_map(|c| c.tags.iter())
            .chain(self.generated.iter().flat_map(|g| g.tags.iter()))
        {
            features.insert(tag.feature().to_string());
        }
        Ok(features)
    }

    /// Compare a result set's case names against the inventory: every
    /// exact case must be reported exactly once; other reports must
    /// fall under a generated prefix (and at most once). A generated
    /// entry carrying an enumeration additionally requires exact leaf
    /// set equality: an unenumerated report and an unreported leaf are
    /// both errors, by name.
    pub fn check_coverage<'a>(
        &self,
        reported: impl IntoIterator<Item = &'a str>,
    ) -> anyhow::Result<()> {
        let inventory: BTreeSet<std::borrow::Cow<'_, str>> =
            self.case.iter().map(|c| c.name.as_str()).collect();
        let mut remaining = inventory.clone();
        let mut remaining_leaves: BTreeMap<&str, BTreeSet<&str>> = self
            .generated
            .iter()
            .filter(|g| !g.cases.is_empty())
            .map(|g| {
                (
                    g.prefix.as_str(),
                    g.cases.iter().map(String::as_str).collect(),
                )
            })
            .collect();
        let mut seen_generated = BTreeSet::new();
        let mut extra = BTreeMap::new();
        for name in reported {
            let key = std::borrow::Cow::Borrowed(name);
            if inventory.contains(&key) {
                if !remaining.remove(&key) {
                    bail!("case `{name}` reported more than once");
                }
            } else if let Some(entry) = self.prefix_of(name) {
                // Generated leaves are the one place reported names
                // aren't pre-validated set members: hold them to the
                // full grammar, or downstream consumers keying
                // artifacts by case name inherit traversal/collision
                // hazards (e.g. `prefix/../../etc/passwd`).
                if let Err(e) = CaseName::parse(name) {
                    bail!("reported case `{name}` under a generated prefix is not a valid case name: {e}");
                }
                if !seen_generated.insert(name.to_string()) {
                    bail!("case `{name}` reported more than once");
                }
                if let Some(leaves) = remaining_leaves.get_mut(entry.prefix.as_str()) {
                    let leaf = &name[entry.prefix.len() + 1..];
                    if !leaves.remove(leaf) {
                        bail!(
                            "case `{name}` is not in the lockfile's enumeration for `{}`",
                            entry.prefix
                        );
                    }
                }
            } else {
                extra.insert(name.to_string(), ());
            }
        }
        if !extra.is_empty() {
            bail!(
                "reported case(s) not in lockfile: {}",
                extra.keys().cloned().collect::<Vec<_>>().join(", ")
            );
        }
        if !remaining.is_empty() {
            bail!(
                "lockfile case(s) without a report: {}",
                remaining
                    .iter()
                    .map(|c| c.as_ref())
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }
        for (prefix, leaves) in &remaining_leaves {
            if !leaves.is_empty() {
                bail!(
                    "generated `{prefix}` leaf(s) without a report: {}",
                    leaves
                        .iter()
                        .map(|l| format!("{prefix}/{l}"))
                        .collect::<Vec<_>>()
                        .join(", ")
                );
            }
        }
        Ok(())
    }

    /// The generated entry covering `name`, if any (longest prefix
    /// wins).
    pub fn prefix_of(&self, name: &str) -> Option<&GeneratedEntry> {
        self.generated
            .iter()
            .filter(|g| component_test_core::name::is_under(name, &g.prefix))
            .max_by_key(|g| g.prefix.len())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(name: &str, tags: &[&str]) -> CaseEntry {
        CaseEntry {
            name: CaseName::parse(name).unwrap(),
            tags: tags.iter().map(|m| Tag::parse(m).unwrap()).collect(),
        }
    }

    fn lockfile(cases: Vec<CaseEntry>) -> Lockfile {
        Lockfile::new(
            SuiteRef {
                name: "sample".into(),
                artifact_sha256: None,
            },
            cases,
        )
    }

    #[test]
    fn roundtrip() {
        let lf = lockfile(vec![
            entry("sample/math/add", &[]),
            entry("sample/hsm/attest", &["hsm"]),
            entry("sample/hsm/declined", &["!hsm"]),
        ]);
        let toml = lf.to_toml().unwrap();
        let back = Lockfile::from_toml(&toml).unwrap();
        assert_eq!(lf, back);
        back.validate().unwrap();
    }

    #[test]
    fn duplicate_names() {
        let lf = lockfile(vec![entry("a/b", &[]), entry("a/b", &[])]);
        assert!(lf.validate().unwrap_err().to_string().contains("duplicate"));
    }

    #[test]
    fn decline_pair_lint() {
        let lf = lockfile(vec![entry("a/pos", &["hsm"])]);
        let err = lf.validate().unwrap_err().to_string();
        assert!(err.contains("decline-pair"), "{err}");

        let lf = lockfile(vec![entry("a/pos", &["hsm"]), entry("a/neg", &["!hsm"])]);
        lf.validate().unwrap();
    }

    #[test]
    fn contradictory_tags_rejected() {
        let lf = lockfile(vec![
            entry("a/pos", &["hsm", "!hsm"]),
            entry("a/neg", &["!hsm"]),
        ]);
        let err = lf.validate().unwrap_err().to_string();
        assert!(err.contains("contradictory"), "{err}");
    }

    #[test]
    fn generated_entries() {
        let mut lf = lockfile(vec![entry("a/pos", &["hsm"]), entry("a/neg", &["!hsm"])]);
        lf.generated.push(GeneratedEntry {
            prefix: "aes-gcm/wycheproof".into(),
            tags: vec![Tag::parse("aes-gcm").unwrap()],
            cases: vec![],
        });
        // decline-pair lint applies to generated tags too
        let err = lf.validate().unwrap_err().to_string();
        assert!(err.contains("aes-gcm"), "{err}");
        lf.generated.push(GeneratedEntry {
            prefix: "aes-gcm/declined".into(),
            tags: vec![Tag::parse("!aes-gcm").unwrap()],
            cases: vec![],
        });
        lf.validate().unwrap();
        // coverage: generated leaves accepted under the prefix
        lf.check_coverage([
            "a/pos",
            "a/neg",
            "aes-gcm/wycheproof/tc1",
            "aes-gcm/wycheproof/tc2/whole",
        ])
        .unwrap();
        assert!(lf
            .check_coverage(["a/pos", "a/neg", "aes-gcm/wycheproofX/tc1"])
            .is_err());
        assert!(lf
            .check_coverage([
                "a/pos",
                "a/neg",
                "aes-gcm/wycheproof/tc1",
                "aes-gcm/wycheproof/tc1"
            ])
            .is_err());
    }

    #[test]
    fn coverage() {
        let lf = lockfile(vec![entry("a/x", &[]), entry("a/y", &[])]);
        lf.check_coverage(["a/x", "a/y"]).unwrap();
        assert!(lf.check_coverage(["a/x"]).is_err());
        assert!(lf.check_coverage(["a/x", "a/y", "a/z"]).is_err());
        assert!(lf.check_coverage(["a/x", "a/x", "a/y"]).is_err());
    }

    #[test]
    fn coverage_validates_generated_leaf_grammar() {
        let mut lf = lockfile(vec![entry("a/x", &[])]);
        lf.generated.push(GeneratedEntry {
            prefix: "a/gen".into(),
            tags: vec![],
            cases: vec![],
        });
        lf.validate().unwrap();
        lf.check_coverage(["a/x", "a/gen/tc1"]).unwrap();
        for bad in [
            "a/gen/../../../etc/passwd",
            "a/gen/UPPER CASE and spaces!",
            "a/gen//empty-segment",
        ] {
            let err = lf.check_coverage(["a/x", bad]).unwrap_err().to_string();
            assert!(err.contains("not a valid case name"), "{bad}: {err}");
        }
    }

    #[test]
    fn validate_checks_generated_prefix_grammar() {
        let mut lf = lockfile(vec![entry("a/x", &[])]);
        lf.generated.push(GeneratedEntry {
            prefix: "Bad_Prefix".into(),
            tags: vec![],
            cases: vec![],
        });
        let err = lf.validate().unwrap_err().to_string();
        assert!(err.contains("not a WIT label"), "{err}");

        let mut lf = lockfile(vec![entry("a/x", &[])]);
        lf.generated.push(GeneratedEntry {
            prefix: "a/375".into(),
            tags: vec![],
            cases: vec![],
        });
        assert!(lf.validate().is_err());
    }

    #[test]
    fn tags_applicability_integration() {
        let e = entry("a/hsm-case", &["hsm", "!sim"]);
        let tags = component_test_core::Tags::new(e.tags.clone()).unwrap();
        assert!(tags.applies(&["sim"]));
        assert!(!tags.applies(&["hsm", "sim"]));
        assert!(!tags.applies::<&str>(&[]));
    }

    fn enumerated(prefix: &str, tags: &[&str], leaves: &[&str]) -> GeneratedEntry {
        GeneratedEntry {
            prefix: prefix.into(),
            tags: tags.iter().map(|m| Tag::parse(m).unwrap()).collect(),
            cases: leaves.iter().map(|s| s.to_string()).collect(),
        }
    }

    /// The emitted TOML is the review surface: enumeration-free output
    /// is byte-identical to the previous serde rendering, and an
    /// enumeration renders one leaf per line.
    #[test]
    fn emission_format() {
        let mut lf = lockfile(vec![entry("a/x", &[]), entry("a/tagged", &["hsm", "!sim"])]);
        lf.suite.artifact_sha256 = Some("cafe".into());
        lf.generated.push(enumerated("a/gen", &[], &[]));
        assert_eq!(
            lf.to_toml().unwrap(),
            "# Generated by component-test; do not edit.\n\
             version = \"0.1\"\n\
             \n[suite]\nname = \"sample\"\nartifact_sha256 = \"cafe\"\n\
             \n[[case]]\nname = \"a/x\"\n\
             \n[[case]]\nname = \"a/tagged\"\ntags = [\"hsm\", \"!sim\"]\n\
             \n[[generated]]\nprefix = \"a/gen\"\n"
        );
        lf.generated[0].cases = vec!["tc1/whole".into(), "tc2".into()];
        assert!(lf.to_toml().unwrap().ends_with(
            "[[generated]]\nprefix = \"a/gen\"\ncases = [\n    \"tc1/whole\",\n    \"tc2\",\n]\n"
        ));
    }

    #[test]
    fn enumerated_roundtrip_and_validate() {
        let mut lf = lockfile(vec![entry("a/x", &[])]);
        lf.generated
            .push(enumerated("a/gen", &[], &["tc1", "tc2/whole"]));
        let back = Lockfile::from_toml(&lf.to_toml().unwrap()).unwrap();
        assert_eq!(lf, back);
        back.validate().unwrap();

        let mut bad = lockfile(vec![entry("a/x", &[])]);
        bad.generated
            .push(enumerated("a/gen", &[], &["tc1", "tc1"]));
        let err = bad.validate().unwrap_err().to_string();
        assert!(err.contains("duplicate leaf"), "{err}");

        let mut bad = lockfile(vec![entry("a/x", &[])]);
        bad.generated
            .push(enumerated("a/gen", &[], &["UPPER CASE"]));
        let err = bad.validate().unwrap_err().to_string();
        assert!(err.contains("leaf `UPPER CASE`"), "{err}");
    }

    /// With an enumeration present, coverage is exact set equality:
    /// an unreported leaf, an unenumerated report, and a same-count
    /// substitution are all errors, by name.
    #[test]
    fn coverage_with_enumeration() {
        let mut lf = lockfile(vec![entry("a/x", &[])]);
        lf.generated.push(enumerated("a/gen", &[], &["tc1", "tc2"]));
        lf.validate().unwrap();
        lf.check_coverage(["a/x", "a/gen/tc1", "a/gen/tc2"])
            .unwrap();

        let err = lf
            .check_coverage(["a/x", "a/gen/tc1"])
            .unwrap_err()
            .to_string();
        assert!(
            err.contains("without a report") && err.contains("a/gen/tc2"),
            "{err}"
        );

        let err = lf
            .check_coverage(["a/x", "a/gen/tc1", "a/gen/tc2", "a/gen/tc3"])
            .unwrap_err()
            .to_string();
        assert!(err.contains("not in the lockfile's enumeration"), "{err}");

        // Substitution: same count, different membership.
        let err = lf
            .check_coverage(["a/x", "a/gen/tc1", "a/gen/tc3"])
            .unwrap_err()
            .to_string();
        assert!(err.contains("a/gen/tc3"), "{err}");

        // An enumeration-free row keeps prefix-granular acceptance.
        let mut open = lockfile(vec![entry("a/x", &[])]);
        open.generated.push(enumerated("a/gen", &[], &[]));
        open.check_coverage(["a/x", "a/gen/anything"]).unwrap();
        open.check_coverage(["a/x"]).unwrap();
    }
}
