//! The inventory lockfile: every case name + its feature tags, in
//! suite order, bound to a suite artifact. TOML, generated, reviewed as
//! diffs.
//!
//! Lints enforced by [`Lockfile::validate`]:
//! - name grammar + duplicate names (hard error)
//! - decline-pair: every feature named by a positive mark is named by
//!   at least one negative-marked case

use std::collections::{BTreeMap, BTreeSet};

use anyhow::{bail, Context as _};
use component_test_core::{CaseName, Tag};
use serde::{Deserialize, Serialize};

pub const LOCKFILE_VERSION: &str = "0.1";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Lockfile {
    /// Format version.
    pub version: String,
    /// The suite this inventory was generated from.
    pub suite: SuiteRef,
    /// Every statically-known case, in canonical order. Empty for
    /// all-generated suites (TOML omits empty table arrays, so this
    /// must default on deserialization or `lock`'s own output for such
    /// a suite wouldn't re-parse).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub case: Vec<CaseEntry>,
    /// Generated rows: leaves enumerated at run time under a static
    /// prefix, sharing the row's tags.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub generated: Vec<GeneratedEntry>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct GeneratedEntry {
    /// Name prefix (every segment a WIT label); cases live at
    /// `prefix/<leaf...>`.
    pub prefix: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<Tag>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct SuiteRef {
    pub name: String,
    /// sha256 of the suite component artifact, hex. Optional while a
    /// suite is under active development; required to publish.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub artifact_sha256: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CaseEntry {
    pub name: CaseName,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<Tag>,
}

impl Lockfile {
    pub fn new(suite: SuiteRef, cases: Vec<CaseEntry>) -> Self {
        Self::with_generated(suite, cases, Vec::new())
    }

    pub fn with_generated(
        suite: SuiteRef,
        cases: Vec<CaseEntry>,
        generated: Vec<GeneratedEntry>,
    ) -> Self {
        Lockfile {
            version: LOCKFILE_VERSION.to_string(),
            suite,
            case: cases,
            generated,
        }
    }

    pub fn to_toml(&self) -> anyhow::Result<String> {
        let body = toml::to_string_pretty(self)?;
        Ok(format!(
            "# Generated by component-test; do not edit.\n{body}"
        ))
    }

    pub fn from_toml(s: &str) -> anyhow::Result<Self> {
        let lf: Lockfile = toml::from_str(s).context("parsing lockfile")?;
        Ok(lf)
    }

    /// Grammar/duplicate/decline-pair lints. Returns the set of features
    /// referenced by tags on success.
    pub fn validate(&self) -> anyhow::Result<BTreeSet<String>> {
        if self.version != LOCKFILE_VERSION {
            bail!("unsupported lockfile version {}", self.version);
        }
        let mut seen = BTreeSet::new();
        let mut positive: BTreeSet<&str> = BTreeSet::new();
        let mut negative: BTreeSet<&str> = BTreeSet::new();
        for entry in &self.case {
            if !seen.insert(entry.name.clone()) {
                bail!("duplicate case name `{}`", entry.name);
            }
            component_test_core::Tags::new(entry.tags.clone())
                .map_err(|e| anyhow::anyhow!("case `{}`: {e}", entry.name))?;
            for mark in &entry.tags {
                if mark.is_negative() {
                    negative.insert(mark.feature());
                } else {
                    positive.insert(mark.feature());
                }
            }
        }
        let mut prefixes = BTreeSet::new();
        for gen in &self.generated {
            if !prefixes.insert(gen.prefix.as_str()) {
                bail!("duplicate generated prefix `{}`", gen.prefix);
            }
            // Same rule the inventory scanner and the macro enforce:
            // every prefix segment is a WIT label (leaves are appended
            // below it). A lockfile is the gate for foreign/hand-made
            // producers, so it must not be the one validator with the
            // hole.
            for seg in gen.prefix.split('/') {
                if let Some(reason) = component_test_core::name::is_wit_label(seg) {
                    bail!(
                        "generated prefix `{}`: segment `{seg}` is not a WIT label ({reason})",
                        gen.prefix
                    );
                }
            }
            component_test_core::Tags::new(gen.tags.clone())
                .map_err(|e| anyhow::anyhow!("generated `{}`: {e}", gen.prefix))?;
            for tag in &gen.tags {
                if tag.is_negative() {
                    negative.insert(tag.feature());
                } else {
                    positive.insert(tag.feature());
                }
            }
        }
        let unpaired: Vec<&&str> = positive.difference(&negative).collect();
        if !unpaired.is_empty() {
            bail!(
                "decline-pair lint: feature(s) {} have positively-marked cases but no \
                 `!feature` decline-asserting case",
                unpaired
                    .iter()
                    .map(|f| format!("`{f}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }
        Ok(positive.union(&negative).map(|s| s.to_string()).collect())
    }

    /// Compare a result set's case names against the inventory: every
    /// exact case must be reported exactly once; other reports must
    /// fall under a generated prefix (and at most once).
    pub fn check_coverage<'a>(
        &self,
        reported: impl IntoIterator<Item = &'a str>,
    ) -> anyhow::Result<()> {
        let inventory: BTreeSet<std::borrow::Cow<'_, str>> =
            self.case.iter().map(|c| c.name.as_str()).collect();
        let mut remaining = inventory.clone();
        let mut seen_generated = BTreeSet::new();
        let mut extra = BTreeMap::new();
        for name in reported {
            let key = std::borrow::Cow::Borrowed(name);
            if inventory.contains(&key) {
                if !remaining.remove(&key) {
                    bail!("case `{name}` reported more than once");
                }
            } else if self.prefix_of(name).is_some() {
                // Generated leaves are the one place reported names
                // aren't pre-validated set members: hold them to the
                // full grammar, or downstream consumers keying
                // artifacts by case name inherit traversal/collision
                // hazards (e.g. `prefix/../../etc/passwd`).
                if let Err(e) = CaseName::parse(name) {
                    bail!("reported case `{name}` under a generated prefix is not a valid case name: {e}");
                }
                if !seen_generated.insert(name.to_string()) {
                    bail!("case `{name}` reported more than once");
                }
            } else {
                extra.insert(name.to_string(), ());
            }
        }
        if !extra.is_empty() {
            bail!(
                "reported case(s) not in lockfile: {}",
                extra.keys().cloned().collect::<Vec<_>>().join(", ")
            );
        }
        if !remaining.is_empty() {
            bail!(
                "lockfile case(s) without a report: {}",
                remaining
                    .iter()
                    .map(|c| c.as_ref())
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }
        Ok(())
    }

    /// The generated entry covering `name`, if any (longest prefix
    /// wins).
    pub fn prefix_of(&self, name: &str) -> Option<&GeneratedEntry> {
        self.generated
            .iter()
            .filter(|g| {
                name.strip_prefix(&g.prefix)
                    .is_some_and(|rest| rest.starts_with('/'))
            })
            .max_by_key(|g| g.prefix.len())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(name: &str, tags: &[&str]) -> CaseEntry {
        CaseEntry {
            name: CaseName::parse(name).unwrap(),
            tags: tags.iter().map(|m| Tag::parse(m).unwrap()).collect(),
        }
    }

    fn lockfile(cases: Vec<CaseEntry>) -> Lockfile {
        Lockfile::new(
            SuiteRef {
                name: "sample".into(),
                artifact_sha256: None,
            },
            cases,
        )
    }

    #[test]
    fn roundtrip() {
        let lf = lockfile(vec![
            entry("sample/math/add", &[]),
            entry("sample/hsm/attest", &["hsm"]),
            entry("sample/hsm/declined", &["!hsm"]),
        ]);
        let toml = lf.to_toml().unwrap();
        let back = Lockfile::from_toml(&toml).unwrap();
        assert_eq!(lf, back);
        back.validate().unwrap();
    }

    #[test]
    fn duplicate_names() {
        let lf = lockfile(vec![entry("a/b", &[]), entry("a/b", &[])]);
        assert!(lf.validate().unwrap_err().to_string().contains("duplicate"));
    }

    #[test]
    fn decline_pair_lint() {
        let lf = lockfile(vec![entry("a/pos", &["hsm"])]);
        let err = lf.validate().unwrap_err().to_string();
        assert!(err.contains("decline-pair"), "{err}");

        let lf = lockfile(vec![entry("a/pos", &["hsm"]), entry("a/neg", &["!hsm"])]);
        lf.validate().unwrap();
    }

    #[test]
    fn contradictory_tags_rejected() {
        let lf = lockfile(vec![
            entry("a/pos", &["hsm", "!hsm"]),
            entry("a/neg", &["!hsm"]),
        ]);
        let err = lf.validate().unwrap_err().to_string();
        assert!(err.contains("contradictory"), "{err}");
    }

    #[test]
    fn generated_entries() {
        let mut lf = lockfile(vec![entry("a/pos", &["hsm"]), entry("a/neg", &["!hsm"])]);
        lf.generated.push(GeneratedEntry {
            prefix: "aes-gcm/wycheproof".into(),
            tags: vec![Tag::parse("aes-gcm").unwrap()],
        });
        // decline-pair lint applies to generated tags too
        let err = lf.validate().unwrap_err().to_string();
        assert!(err.contains("aes-gcm"), "{err}");
        lf.generated.push(GeneratedEntry {
            prefix: "aes-gcm/declined".into(),
            tags: vec![Tag::parse("!aes-gcm").unwrap()],
        });
        lf.validate().unwrap();
        // coverage: generated leaves accepted under the prefix
        lf.check_coverage([
            "a/pos",
            "a/neg",
            "aes-gcm/wycheproof/tc1",
            "aes-gcm/wycheproof/tc2/whole",
        ])
        .unwrap();
        assert!(lf
            .check_coverage(["a/pos", "a/neg", "aes-gcm/wycheproofX/tc1"])
            .is_err());
        assert!(lf
            .check_coverage([
                "a/pos",
                "a/neg",
                "aes-gcm/wycheproof/tc1",
                "aes-gcm/wycheproof/tc1"
            ])
            .is_err());
    }

    #[test]
    fn coverage() {
        let lf = lockfile(vec![entry("a/x", &[]), entry("a/y", &[])]);
        lf.check_coverage(["a/x", "a/y"]).unwrap();
        assert!(lf.check_coverage(["a/x"]).is_err());
        assert!(lf.check_coverage(["a/x", "a/y", "a/z"]).is_err());
        assert!(lf.check_coverage(["a/x", "a/x", "a/y"]).is_err());
    }

    #[test]
    fn coverage_validates_generated_leaf_grammar() {
        let mut lf = lockfile(vec![entry("a/x", &[])]);
        lf.generated.push(GeneratedEntry {
            prefix: "a/gen".into(),
            tags: vec![],
        });
        lf.validate().unwrap();
        lf.check_coverage(["a/x", "a/gen/tc1"]).unwrap();
        for bad in [
            "a/gen/../../../etc/passwd",
            "a/gen/UPPER CASE and spaces!",
            "a/gen//empty-segment",
        ] {
            let err = lf.check_coverage(["a/x", bad]).unwrap_err().to_string();
            assert!(err.contains("not a valid case name"), "{bad}: {err}");
        }
    }

    #[test]
    fn validate_checks_generated_prefix_grammar() {
        let mut lf = lockfile(vec![entry("a/x", &[])]);
        lf.generated.push(GeneratedEntry {
            prefix: "Bad_Prefix".into(),
            tags: vec![],
        });
        let err = lf.validate().unwrap_err().to_string();
        assert!(err.contains("not a WIT label"), "{err}");

        let mut lf = lockfile(vec![entry("a/x", &[])]);
        lf.generated.push(GeneratedEntry {
            prefix: "a/375".into(),
            tags: vec![],
        });
        assert!(lf.validate().is_err());
    }

    #[test]
    fn tags_applicability_integration() {
        let e = entry("a/hsm-case", &["hsm", "!sim"]);
        let tags = component_test_core::Tags::new(e.tags.clone()).unwrap();
        assert!(tags.applies(&["sim"]));
        assert!(!tags.applies(&["hsm", "sim"]));
        assert!(!tags.applies::<&str>(&[]));
    }
}
