//! The inventory lockfile: every case name + its feature marks, in
//! suite order, bound to a suite artifact. TOML, generated, reviewed as
//! diffs.
//!
//! Lints enforced by [`Lockfile::validate`]:
//! - name grammar + duplicate names (hard error)
//! - decline-pair: every feature named by a positive mark is named by
//!   at least one negative-marked case

use std::collections::{BTreeMap, BTreeSet};

use anyhow::{bail, Context as _};
use component_test_core::{CaseName, Mark};
use serde::{Deserialize, Serialize};

pub const LOCKFILE_VERSION: &str = "0.1";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Lockfile {
    /// Format version.
    pub version: String,
    /// The suite this inventory was generated from.
    pub suite: SuiteRef,
    /// Every case, in suite order.
    pub case: Vec<CaseEntry>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct SuiteRef {
    pub name: String,
    /// sha256 of the suite component artifact, hex. Optional while a
    /// suite is under active development; required to publish.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub artifact_sha256: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CaseEntry {
    pub name: CaseName,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub marks: Vec<Mark>,
}

impl Lockfile {
    pub fn new(suite: SuiteRef, cases: Vec<CaseEntry>) -> Self {
        Lockfile {
            version: LOCKFILE_VERSION.to_string(),
            suite,
            case: cases,
        }
    }

    pub fn to_toml(&self) -> anyhow::Result<String> {
        let body = toml::to_string_pretty(self)?;
        Ok(format!(
            "# Generated by component-test; do not edit.\n{body}"
        ))
    }

    pub fn from_toml(s: &str) -> anyhow::Result<Self> {
        let lf: Lockfile = toml::from_str(s).context("parsing lockfile")?;
        Ok(lf)
    }

    /// Grammar/duplicate/decline-pair lints. Returns the set of features
    /// referenced by marks on success.
    pub fn validate(&self) -> anyhow::Result<BTreeSet<String>> {
        if self.version != LOCKFILE_VERSION {
            bail!("unsupported lockfile version {}", self.version);
        }
        let mut seen = BTreeSet::new();
        let mut positive: BTreeSet<&str> = BTreeSet::new();
        let mut negative: BTreeSet<&str> = BTreeSet::new();
        for entry in &self.case {
            if !seen.insert(entry.name.as_str()) {
                bail!("duplicate case name `{}`", entry.name);
            }
            for mark in &entry.marks {
                if mark.is_negative() {
                    negative.insert(mark.feature());
                } else {
                    positive.insert(mark.feature());
                }
            }
        }
        let unpaired: Vec<&&str> = positive.difference(&negative).collect();
        if !unpaired.is_empty() {
            bail!(
                "decline-pair lint: feature(s) {} have positively-marked cases but no \
                 `!feature` decline-asserting case",
                unpaired
                    .iter()
                    .map(|f| format!("`{f}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }
        Ok(positive
            .union(&negative)
            .map(|s| s.to_string())
            .collect())
    }

    /// Compare a result set's case names against the inventory:
    /// executed-or-excluded coverage must exactly match.
    pub fn check_coverage<'a>(
        &self,
        reported: impl IntoIterator<Item = &'a str>,
    ) -> anyhow::Result<()> {
        let inventory: BTreeSet<&str> = self.case.iter().map(|c| c.name.as_str()).collect();
        let mut remaining = inventory.clone();
        let mut extra = BTreeMap::new();
        for name in reported {
            if !inventory.contains(name) {
                extra.insert(name.to_string(), ());
            } else if !remaining.remove(name) {
                bail!("case `{name}` reported more than once");
            }
        }
        if !extra.is_empty() {
            bail!(
                "reported case(s) not in lockfile: {}",
                extra.keys().cloned().collect::<Vec<_>>().join(", ")
            );
        }
        if !remaining.is_empty() {
            bail!(
                "lockfile case(s) without a report: {}",
                remaining.iter().copied().collect::<Vec<_>>().join(", ")
            );
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(name: &str, marks: &[&str]) -> CaseEntry {
        CaseEntry {
            name: CaseName::parse(name).unwrap(),
            marks: marks.iter().map(|m| Mark::parse(m).unwrap()).collect(),
        }
    }

    fn lockfile(cases: Vec<CaseEntry>) -> Lockfile {
        Lockfile::new(
            SuiteRef {
                name: "sample".into(),
                artifact_sha256: None,
            },
            cases,
        )
    }

    #[test]
    fn roundtrip() {
        let lf = lockfile(vec![
            entry("sample/math/add", &[]),
            entry("sample/hsm/attest", &["hsm"]),
            entry("sample/hsm/declined", &["!hsm"]),
        ]);
        let toml = lf.to_toml().unwrap();
        let back = Lockfile::from_toml(&toml).unwrap();
        assert_eq!(lf, back);
        back.validate().unwrap();
    }

    #[test]
    fn duplicate_names() {
        let lf = lockfile(vec![entry("a/b", &[]), entry("a/b", &[])]);
        assert!(lf.validate().unwrap_err().to_string().contains("duplicate"));
    }

    #[test]
    fn decline_pair_lint() {
        let lf = lockfile(vec![entry("a/pos", &["hsm"])]);
        let err = lf.validate().unwrap_err().to_string();
        assert!(err.contains("decline-pair"), "{err}");

        let lf = lockfile(vec![entry("a/pos", &["hsm"]), entry("a/neg", &["!hsm"])]);
        lf.validate().unwrap();
    }

    #[test]
    fn coverage() {
        let lf = lockfile(vec![entry("a/x", &[]), entry("a/y", &[])]);
        lf.check_coverage(["a/x", "a/y"]).unwrap();
        assert!(lf.check_coverage(["a/x"]).is_err());
        assert!(lf.check_coverage(["a/x", "a/y", "a/z"]).is_err());
        assert!(lf.check_coverage(["a/x", "a/x", "a/y"]).is_err());
    }

    #[test]
    fn marks_applicability_integration() {
        
        let e = entry("a/hsm-case", &["hsm", "!sim"]);
        let marks = component_test_core::Marks(e.marks.clone());
        assert!(marks.applies(&["sim"]));
        assert!(!marks.applies(&["hsm", "sim"]));
        assert!(!marks.applies::<&str>(&[]));
    }
}
